### PR TITLE
Fix Mongoose instrumentation when awaited; add basic MongoDB tests

### PR DESCRIPTION
**Pull request by djanowski**
https://github.com/honeycombio/beeline-nodejs/issues/199

Build expected to fail like this:

```
FAIL  lib/instrumentation/mongodb.test.js
  ● mongodb › cursors › find › with query, no results

    expect(received).toBeGreaterThan(expected)

    Expected: > 1
    Received:   0.145807

      60 |           expect(event.name).toEqual("collection.find");
      61 |           expect(event["db.query"]).toMatchObject({ name: "Bob" });
    > 62 |           expect(event["duration_ms"]).toBeGreaterThan(1);
         |                                        ^
      63 |         });
      64 |       });
      65 |

      at lib/instrumentation/mongodb.test.js:62:40
      at withDB (lib/instrumentation/mongodb.test.js:101:5)
      at Object.<anonymous> (lib/instrumentation/mongodb.test.js:48:9)

  ● mongodb › cursors › find › with query, some results

    expect(received).toBeGreaterThan(expected)

    Expected: > 1
    Received:   0.143061

      81 |           expect(event.name).toEqual("collection.find");
      82 |           expect(event["db.query"]).toMatchObject({ name: "Bob" });
    > 83 |           expect(event["duration_ms"]).toBeGreaterThan(1);
         |                                        ^
      84 |         });
      85 |       });
      86 |     });

      at lib/instrumentation/mongodb.test.js:83:40
      at withDB (lib/instrumentation/mongodb.test.js:101:5)
      at Object.<anonymous> (lib/instrumentation/mongodb.test.js:69:9)

 PASS  lib/instrumentation/express.test.js
 PASS  lib/deterministic_sampler.test.js (5.695 s)

Test Suites: 1 failed, 18 passed, 19 total
Tests:       2 failed, 187 passed, 189 total
Snapshots:   0 total
Time:        6.23 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

### CODE REVIEW

**Review by robbkidd — CHANGES_REQUESTED** [review]
@djanowski Thank you for your PRs!

It would help to review the tests and the fix together. This branch already has the commit for the new tests. I recommend adding [the commit with the fix](https://github.com/honeycombio/beeline-nodejs/pull/394/commits/cbfba0f377804845786348127f8e500311f44ae0) to this PR. It will then be clear that the fix makes those tests pass.

**Comment by djanowski** [comment]
@robbkidd Thanks for your feedback! And done.

**Comment by robbkidd** [comment]
red tests, then green tests

red light, then green light

**Review by robbkidd — COMMENTED** [review]
These changes fail to emit any spans for Mongo queries when used in an ad-hoc Express+Mongo app. It seems to lose track of its place in the tracker's context stack. I suspect the Dark Arts. Have you tested these changes in an app outside of the unit tests added?

This does not seem to address [the Mongoose issue](https://github.com/honeycombio/beeline-nodejs/issues/199), either.

**Comment by djanowski** [comment]
Hi Robb, I didn't get any notifications about your review, sorry.

> These changes fail to emit any spans for Mongo queries when used in an ad-hoc Express+Mongo app. It seems to lose track of its place in the tracker's context stack. I suspect the Dark Arts. Have you tested these changes in an app outside of the unit tests added?

Do you have that standalone Express+Mongo app at hand? Maybe I can incorporate it to the test suite.

> This does not seem to address [the Mongoose issue](https://github.com/honeycombio/beeline-nodejs/issues/199), either.

This PR does fix the issue of MongoDB/Mongoose query durations not being correctly tracked. Unless you mean some other issue?

**Comment by vreynolds** [comment]
Hey @djanowski ,

Here's the server we tested with:

```js
require("honeycomb-beeline")({
  writeKey: "",
  dataset: "node-mongo",
  serviceName: "node-service",
  mongodb: {
    includeDocuments: true,
  },
});


const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });
const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function () {
  console.log("CONNECTED! WE ARE IN")
});
const kittySchema = new mongoose.Schema({
  name: String
});
const Kitten = mongoose.model('Kitten', kittySchema);

const express = require('express');
const app = express();
const bodyParser = require('body-parser');
app.use(bodyParser.json());

app.get('/await-kitten', async (req, res) => {
  try {
    const kittens = await Kitten.find({ name: "meowitz" })
    res.send(kittens)
  } catch {
    res.send("ERROR!: ", err)
  }
})

app.get('/kitten', (req, res) => {
  Kitten.find({}, function (err, kittens) {
    if (err) {
      res.send("ERROR!: ", err)
      return;
    }
    res.send(kittens)
  })
})

app.post('/kitten', (req, res) => {
  const kit = new Kitten({ name: req.body.name });
  kit.save(function (err, kit) {
    if (err) {
      res.send("ERROR!: ", err)
      return;
    }
    res.send("OK")
  })
})

app.listen(3000, () => {
  console.log("listening on 3000")
})

```

Using published beeline:
- POST `/kitten` is traced
- GET `/kitten` is traced
- GET `/await-kitten` is **not** traced (which is the issue you referenced here #199 )

Using the beeline build from this PR:
- POST `/kitten` is traced
- GET `/kitten` is **not** traced
- GET `/await-kitten` is **not** traced

So the concern is that GET `/kitten` is no longer traced, which is a regression. The `/await-kitten` issue sounds like is separate from what you set out to fix (durations).

**Comment by MikeGoldsmith** [comment]
We're going to close this for now as it's had low activity. Feel free to re-open if it’s still relevant.

**Pull request closed without merging**
